[global]
#
# Default Data Set
#
twoStepFlag             1
priority1               1
priority2               2
domainNumber            10

#
# Port Data Set
#
logAnnounceInterval     0
logSyncInterval         -3
logMinDelayReqInterval  -3
logMinPdelayReqInterval -3
announceReceiptTimeout  3
syncReceiptTimeout      0

